Update husky pre commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,13 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+echo -e "Formatting only staged files\n"
 nr precommit
+
+echo -e "Checking lint errors on staged files\n"
+nr lint --cache
+
+if [ $? -ne 0 ]; then
+    echo -e "Lint error\n"
+    exit 1
+fi
